version: '3.8'

services:
  app:
    build:
      context: .
    command: npm run start
    environment:
      - DB_CLIENT=mysql
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_SCHEMA=skore_challenge
      - DB_PORT=3306
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - net
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=skore_challenge
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
    ports:
      - '3305:3306'
    networks:
      - net
networks:
  net:
    driver: bridge
